name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.6]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
          export ARWEN_PATH=${GITHUB_WORKSPACE}/Arwen/arwen
          mkdir ${GITHUB_WORKSPACE}/Arwen
          make test
